version: '3.9'
services:
  db:
    image: postgres
    ports:
      - '5555:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      PG_DATA: /var/lib/postgresql/data/pgdata

volumes:
  db-data:
